spring.application.name=link-shortener-spring-admin

admin.username=bpiatek
admin.password=dupa1234


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=read_only