replicaCount: 1

image:
  repository: link-shortener-spring-admin
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  name: link-shortener-spring-admin

spring:
  profiles:
    active: "default"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  hostname: "api.local"

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0"